package org.bot.users;

public enum UserState {
    NOT_ON_RECORD,
    USER, USR_ADD_COACH, USR_DELETE_COACH,
    ADMIN,
    ADD_ADMIN, ADM_ADD_COACH, ADM_DELETE_COACH,
    ADD_NAME, ADD_SCHEDULE, ADD_INFO,
    EDIT_NAME, EDIT_SCHEDULE, EDIT_INFO
}
