package org.bot.users;

public enum UserState {
    NOT_ON_RECORD,
    USER, USR_ADD_COACH, USR_DELETE_COACH,
    ADMIN,
    SELECTING_RECEIVERS, SELECTING_MESSAGE,
    ADD_NICK, ADD_SCHEDULE, ADD_INFO, ADMIN_DELETE_COACH,
    SELECTING_COACH_FOR_CHANGES, CHANGING_SCHEDULE,
    ADD_ADMIN, DELETE_ADMIN
}
